{% set name = "autoreject" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2154a93d7d5a297ad10e8e34b849bb922b7a6d09383ddf8ab396224dfcacf4f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.20.2
    - scipy >=1.6.3
    - mne-base >=1.0
    - scikit-learn >=0.24.2
    - joblib
    - matplotlib-base >=3.4
    - tqdm
    - h5io

test:
  imports:
    - autoreject
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import autoreject; assert autoreject.__version__ == '{{ version }}', autoreject.__version__"

about:
  home: https://autoreject.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automatically reject bad trials and repair bad sensors in M/EEG data.
  dev_url: https://github.com/autoreject/autoreject

extra:
  recipe-maintainers:
    - sappelhoff
    - hoechenberger
    - larsoner
